model: BaseGNN
run_name: base_0
adj_init: Random
adj_sym: true
input_feat_dim: 48
n_channels: 64
base_criterion: MSE
regularization:
- L1
- Acyclic
regularization_gamma:
- 0.0001
- 0.0001
data_path: C:\Users\Vladimir\PycharmProjects\EEGPatternRecognition\matrix_dataset
train_bs: 1024
test_bs: 1024
num_epoch: 25
is_binary: false
lr: 0.0001

